# Generated by Django 6.0.2 on 2026-02-20 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('document', models.FileField(upload_to='documents/')),
                ('Blog_detail', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Blog_App.users')),
            ],
        ),
    ]
